// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/friend/friend.proto

package friend

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PostReq struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostReq) Reset()         { *m = PostReq{} }
func (m *PostReq) String() string { return proto.CompactTextString(m) }
func (*PostReq) ProtoMessage()    {}
func (*PostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{1}
}

func (m *PostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostReq.Unmarshal(m, b)
}
func (m *PostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostReq.Marshal(b, m, deterministic)
}
func (m *PostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostReq.Merge(m, src)
}
func (m *PostReq) XXX_Size() int {
	return xxx_messageInfo_PostReq.Size(m)
}
func (m *PostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PostReq.DiscardUnknown(m)
}

var xxx_messageInfo_PostReq proto.InternalMessageInfo

func (m *PostReq) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *PostReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type PostResp struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResp) Reset()         { *m = PostResp{} }
func (m *PostResp) String() string { return proto.CompactTextString(m) }
func (*PostResp) ProtoMessage()    {}
func (*PostResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{2}
}

func (m *PostResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResp.Unmarshal(m, b)
}
func (m *PostResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResp.Marshal(b, m, deterministic)
}
func (m *PostResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResp.Merge(m, src)
}
func (m *PostResp) XXX_Size() int {
	return xxx_messageInfo_PostResp.Size(m)
}
func (m *PostResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResp.DiscardUnknown(m)
}

var xxx_messageInfo_PostResp proto.InternalMessageInfo

func (m *PostResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DelByUserIDReq struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelByUserIDReq) Reset()         { *m = DelByUserIDReq{} }
func (m *DelByUserIDReq) String() string { return proto.CompactTextString(m) }
func (*DelByUserIDReq) ProtoMessage()    {}
func (*DelByUserIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{3}
}

func (m *DelByUserIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelByUserIDReq.Unmarshal(m, b)
}
func (m *DelByUserIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelByUserIDReq.Marshal(b, m, deterministic)
}
func (m *DelByUserIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelByUserIDReq.Merge(m, src)
}
func (m *DelByUserIDReq) XXX_Size() int {
	return xxx_messageInfo_DelByUserIDReq.Size(m)
}
func (m *DelByUserIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelByUserIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelByUserIDReq proto.InternalMessageInfo

func (m *DelByUserIDReq) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *DelByUserIDReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DelByUserIDResp struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelByUserIDResp) Reset()         { *m = DelByUserIDResp{} }
func (m *DelByUserIDResp) String() string { return proto.CompactTextString(m) }
func (*DelByUserIDResp) ProtoMessage()    {}
func (*DelByUserIDResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{4}
}

func (m *DelByUserIDResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelByUserIDResp.Unmarshal(m, b)
}
func (m *DelByUserIDResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelByUserIDResp.Marshal(b, m, deterministic)
}
func (m *DelByUserIDResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelByUserIDResp.Merge(m, src)
}
func (m *DelByUserIDResp) XXX_Size() int {
	return xxx_messageInfo_DelByUserIDResp.Size(m)
}
func (m *DelByUserIDResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelByUserIDResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelByUserIDResp proto.InternalMessageInfo

func (m *DelByUserIDResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CheckIsFriendReq struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckIsFriendReq) Reset()         { *m = CheckIsFriendReq{} }
func (m *CheckIsFriendReq) String() string { return proto.CompactTextString(m) }
func (*CheckIsFriendReq) ProtoMessage()    {}
func (*CheckIsFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{5}
}

func (m *CheckIsFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckIsFriendReq.Unmarshal(m, b)
}
func (m *CheckIsFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckIsFriendReq.Marshal(b, m, deterministic)
}
func (m *CheckIsFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckIsFriendReq.Merge(m, src)
}
func (m *CheckIsFriendReq) XXX_Size() int {
	return xxx_messageInfo_CheckIsFriendReq.Size(m)
}
func (m *CheckIsFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckIsFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckIsFriendReq proto.InternalMessageInfo

func (m *CheckIsFriendReq) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *CheckIsFriendReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CheckIsFriendResp struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Result               bool     `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckIsFriendResp) Reset()         { *m = CheckIsFriendResp{} }
func (m *CheckIsFriendResp) String() string { return proto.CompactTextString(m) }
func (*CheckIsFriendResp) ProtoMessage()    {}
func (*CheckIsFriendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{6}
}

func (m *CheckIsFriendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckIsFriendResp.Unmarshal(m, b)
}
func (m *CheckIsFriendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckIsFriendResp.Marshal(b, m, deterministic)
}
func (m *CheckIsFriendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckIsFriendResp.Merge(m, src)
}
func (m *CheckIsFriendResp) XXX_Size() int {
	return xxx_messageInfo_CheckIsFriendResp.Size(m)
}
func (m *CheckIsFriendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckIsFriendResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckIsFriendResp proto.InternalMessageInfo

func (m *CheckIsFriendResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *CheckIsFriendResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type GetListReq struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListReq) Reset()         { *m = GetListReq{} }
func (m *GetListReq) String() string { return proto.CompactTextString(m) }
func (*GetListReq) ProtoMessage()    {}
func (*GetListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{7}
}

func (m *GetListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListReq.Unmarshal(m, b)
}
func (m *GetListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListReq.Marshal(b, m, deterministic)
}
func (m *GetListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListReq.Merge(m, src)
}
func (m *GetListReq) XXX_Size() int {
	return xxx_messageInfo_GetListReq.Size(m)
}
func (m *GetListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetListReq proto.InternalMessageInfo

func (m *GetListReq) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

type GetListResp struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	List                 []string `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListResp) Reset()         { *m = GetListResp{} }
func (m *GetListResp) String() string { return proto.CompactTextString(m) }
func (*GetListResp) ProtoMessage()    {}
func (*GetListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{8}
}

func (m *GetListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResp.Unmarshal(m, b)
}
func (m *GetListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResp.Marshal(b, m, deterministic)
}
func (m *GetListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResp.Merge(m, src)
}
func (m *GetListResp) XXX_Size() int {
	return xxx_messageInfo_GetListResp.Size(m)
}
func (m *GetListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResp proto.InternalMessageInfo

func (m *GetListResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetListResp) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "nezha.chat.friend.srv.service.Error")
	proto.RegisterType((*PostReq)(nil), "nezha.chat.friend.srv.service.PostReq")
	proto.RegisterType((*PostResp)(nil), "nezha.chat.friend.srv.service.PostResp")
	proto.RegisterType((*DelByUserIDReq)(nil), "nezha.chat.friend.srv.service.DelByUserIDReq")
	proto.RegisterType((*DelByUserIDResp)(nil), "nezha.chat.friend.srv.service.DelByUserIDResp")
	proto.RegisterType((*CheckIsFriendReq)(nil), "nezha.chat.friend.srv.service.CheckIsFriendReq")
	proto.RegisterType((*CheckIsFriendResp)(nil), "nezha.chat.friend.srv.service.CheckIsFriendResp")
	proto.RegisterType((*GetListReq)(nil), "nezha.chat.friend.srv.service.GetListReq")
	proto.RegisterType((*GetListResp)(nil), "nezha.chat.friend.srv.service.GetListResp")
}

func init() { proto.RegisterFile("proto/friend/friend.proto", fileDescriptor_f54247b80b303e7a) }

var fileDescriptor_f54247b80b303e7a = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x4b, 0x2a, 0x41,
	0x14, 0xbf, 0xde, 0xd5, 0x55, 0x8f, 0xdc, 0x7b, 0xbd, 0xe7, 0x21, 0x6c, 0x21, 0x90, 0x21, 0xcc,
	0x02, 0xc7, 0xb0, 0xb7, 0x7a, 0x33, 0x33, 0x84, 0x82, 0x18, 0xe8, 0xa1, 0xa0, 0x07, 0xdd, 0x9d,
	0x74, 0xd1, 0x76, 0x6d, 0x66, 0x14, 0xea, 0x7f, 0xea, 0x7f, 0x8c, 0x99, 0x9d, 0x3e, 0xf4, 0xa1,
	0xf5, 0xe3, 0xc9, 0x73, 0xdc, 0xdf, 0xd7, 0xf2, 0x3b, 0x2c, 0xec, 0x4e, 0x45, 0xac, 0xe2, 0xe6,
	0xa3, 0x08, 0x79, 0x14, 0xd8, 0x1f, 0x6a, 0xfe, 0xc3, 0xbd, 0x88, 0xbf, 0x8e, 0xfa, 0xd4, 0x1f,
	0xf5, 0x15, 0xb5, 0x0f, 0xa4, 0x98, 0x53, 0xc9, 0xc5, 0x3c, 0xf4, 0x39, 0x69, 0x40, 0xee, 0x42,
	0x88, 0x58, 0x20, 0x42, 0xd6, 0x8f, 0x03, 0x5e, 0xc9, 0x54, 0x33, 0x75, 0x87, 0x99, 0x19, 0xcb,
	0xe0, 0x3c, 0xc9, 0x61, 0xe5, 0x77, 0x35, 0x53, 0x2f, 0x32, 0x3d, 0x92, 0x33, 0xc8, 0xdf, 0xc4,
	0x52, 0x31, 0xfe, 0x8c, 0x15, 0xc8, 0xab, 0x78, 0xcc, 0xa3, 0x5e, 0x60, 0x38, 0x45, 0xf6, 0xb1,
	0xe2, 0x0e, 0xb8, 0x33, 0xc9, 0x45, 0x2f, 0xb0, 0x4c, 0xbb, 0x91, 0x2e, 0x14, 0x12, 0xb2, 0x9c,
	0xe2, 0x29, 0xe4, 0xb8, 0xf6, 0x35, 0xdc, 0x52, 0x6b, 0x9f, 0xfe, 0x18, 0x93, 0x9a, 0x8c, 0x2c,
	0xa1, 0x90, 0x36, 0xfc, 0xed, 0xf0, 0x49, 0xfb, 0xe5, 0x56, 0xcb, 0x76, 0x36, 0xcb, 0x72, 0x0d,
	0xff, 0x16, 0x34, 0xb6, 0x8c, 0xd4, 0x81, 0xf2, 0xf9, 0x88, 0xfb, 0xe3, 0x9e, 0xec, 0x1a, 0xe4,
	0x66, 0xa1, 0x86, 0xf0, 0x7f, 0x49, 0x65, 0xbb, 0x58, 0xda, 0x48, 0x70, 0x39, 0x9b, 0x28, 0x63,
	0x54, 0x60, 0x76, 0x23, 0x35, 0x80, 0x4b, 0xae, 0xae, 0xc2, 0x94, 0x26, 0xc9, 0x03, 0x94, 0x3e,
	0x71, 0x5b, 0x46, 0x41, 0xc8, 0x4e, 0x42, 0xa9, 0x83, 0x38, 0xf5, 0x22, 0x33, 0x73, 0xeb, 0xcd,
	0x01, 0x37, 0x79, 0x53, 0xbc, 0x83, 0xac, 0xbe, 0x0d, 0xac, 0xa5, 0x68, 0xda, 0xeb, 0xf3, 0x0e,
	0x56, 0xc2, 0xc9, 0x29, 0xf9, 0x85, 0x11, 0x94, 0xbe, 0x55, 0x8d, 0x8d, 0x14, 0xe6, 0xe2, 0x69,
	0x79, 0x74, 0x1d, 0xb8, 0xf1, 0x53, 0xf0, 0x67, 0xa1, 0x45, 0x6c, 0xa6, 0x48, 0x2c, 0x5f, 0x8e,
	0x77, 0xbc, 0x1e, 0xc1, 0xb8, 0x0e, 0x20, 0x6f, 0xab, 0xc2, 0xc3, 0x14, 0xfa, 0x57, 0xf5, 0xde,
	0xd1, 0xaa, 0x50, 0xed, 0xd1, 0x2e, 0xdc, 0xbb, 0x09, 0x66, 0xe0, 0x9a, 0x8f, 0xcb, 0xc9, 0x7b,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0x70, 0x03, 0xca, 0x79, 0x04, 0x00, 0x00,
}
