// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/chat/chat.proto

package chat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_411570473cc66b06, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PostReq struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostReq) Reset()         { *m = PostReq{} }
func (m *PostReq) String() string { return proto.CompactTextString(m) }
func (*PostReq) ProtoMessage()    {}
func (*PostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_411570473cc66b06, []int{1}
}

func (m *PostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostReq.Unmarshal(m, b)
}
func (m *PostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostReq.Marshal(b, m, deterministic)
}
func (m *PostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostReq.Merge(m, src)
}
func (m *PostReq) XXX_Size() int {
	return xxx_messageInfo_PostReq.Size(m)
}
func (m *PostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PostReq.DiscardUnknown(m)
}

var xxx_messageInfo_PostReq proto.InternalMessageInfo

func (m *PostReq) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *PostReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PostReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PostResp struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResp) Reset()         { *m = PostResp{} }
func (m *PostResp) String() string { return proto.CompactTextString(m) }
func (*PostResp) ProtoMessage()    {}
func (*PostResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_411570473cc66b06, []int{2}
}

func (m *PostResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResp.Unmarshal(m, b)
}
func (m *PostResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResp.Marshal(b, m, deterministic)
}
func (m *PostResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResp.Merge(m, src)
}
func (m *PostResp) XXX_Size() int {
	return xxx_messageInfo_PostResp.Size(m)
}
func (m *PostResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResp.DiscardUnknown(m)
}

var xxx_messageInfo_PostResp proto.InternalMessageInfo

func (m *PostResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetQueueReq struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQueueReq) Reset()         { *m = GetQueueReq{} }
func (m *GetQueueReq) String() string { return proto.CompactTextString(m) }
func (*GetQueueReq) ProtoMessage()    {}
func (*GetQueueReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_411570473cc66b06, []int{3}
}

func (m *GetQueueReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQueueReq.Unmarshal(m, b)
}
func (m *GetQueueReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQueueReq.Marshal(b, m, deterministic)
}
func (m *GetQueueReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQueueReq.Merge(m, src)
}
func (m *GetQueueReq) XXX_Size() int {
	return xxx_messageInfo_GetQueueReq.Size(m)
}
func (m *GetQueueReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQueueReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetQueueReq proto.InternalMessageInfo

func (m *GetQueueReq) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

type GetQueueResp struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Queue                string   `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQueueResp) Reset()         { *m = GetQueueResp{} }
func (m *GetQueueResp) String() string { return proto.CompactTextString(m) }
func (*GetQueueResp) ProtoMessage()    {}
func (*GetQueueResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_411570473cc66b06, []int{4}
}

func (m *GetQueueResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQueueResp.Unmarshal(m, b)
}
func (m *GetQueueResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQueueResp.Marshal(b, m, deterministic)
}
func (m *GetQueueResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQueueResp.Merge(m, src)
}
func (m *GetQueueResp) XXX_Size() int {
	return xxx_messageInfo_GetQueueResp.Size(m)
}
func (m *GetQueueResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQueueResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetQueueResp proto.InternalMessageInfo

func (m *GetQueueResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetQueueResp) GetQueue() string {
	if m != nil {
		return m.Queue
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "nezha.chat.chat.srv.service.Error")
	proto.RegisterType((*PostReq)(nil), "nezha.chat.chat.srv.service.PostReq")
	proto.RegisterType((*PostResp)(nil), "nezha.chat.chat.srv.service.PostResp")
	proto.RegisterType((*GetQueueReq)(nil), "nezha.chat.chat.srv.service.GetQueueReq")
	proto.RegisterType((*GetQueueResp)(nil), "nezha.chat.chat.srv.service.GetQueueResp")
}

func init() { proto.RegisterFile("proto/chat/chat.proto", fileDescriptor_411570473cc66b06) }

var fileDescriptor_411570473cc66b06 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x36, 0x49, 0xdb, 0xa9, 0x07, 0x19, 0x54, 0x42, 0xbd, 0x94, 0x45, 0x31, 0x1e, 0x5c,
	0xa1, 0x5e, 0x3c, 0xfb, 0x81, 0xf4, 0xa6, 0x0b, 0xbd, 0x78, 0x10, 0xd6, 0x64, 0x68, 0x44, 0xda,
	0x4d, 0x77, 0x37, 0x3d, 0xf8, 0xeb, 0xfc, 0x69, 0xb2, 0x9b, 0x2d, 0x7a, 0x0a, 0x05, 0x2f, 0xc3,
	0xbc, 0xe5, 0xbd, 0x37, 0x6f, 0x86, 0x85, 0xe3, 0x5a, 0x2b, 0xab, 0xae, 0x8b, 0x4a, 0x5a, 0x5f,
	0xb8, 0xc7, 0x78, 0xba, 0xa2, 0xaf, 0x4a, 0x72, 0xff, 0xe2, 0x8b, 0xd1, 0x1b, 0x6e, 0x48, 0x6f,
	0x3e, 0x0a, 0x62, 0x57, 0x90, 0x3c, 0x6a, 0xad, 0x34, 0x22, 0xc4, 0x85, 0x2a, 0x29, 0x8b, 0x26,
	0x51, 0xde, 0x13, 0xbe, 0xc7, 0x43, 0xe8, 0x2d, 0xcd, 0x22, 0xdb, 0x9f, 0x44, 0xf9, 0x50, 0xb8,
	0x96, 0xcd, 0xa1, 0xff, 0xac, 0x8c, 0x15, 0xb4, 0xc6, 0x0c, 0xfa, 0x56, 0x7d, 0xd2, 0x6a, 0x56,
	0x7a, 0xcd, 0x50, 0x6c, 0x21, 0x9e, 0x40, 0xda, 0x18, 0xd2, 0xb3, 0x32, 0x28, 0x03, 0x72, 0x8a,
	0x25, 0x19, 0x23, 0x17, 0x94, 0xf5, 0x5a, 0x45, 0x80, 0xec, 0x01, 0x06, 0xad, 0xad, 0xa9, 0xf1,
	0x16, 0x12, 0x72, 0x89, 0xbc, 0xeb, 0x68, 0xca, 0x78, 0x47, 0x7c, 0xee, 0xb3, 0x8b, 0x56, 0xc0,
	0x2e, 0x60, 0xf4, 0x44, 0xf6, 0xa5, 0xa1, 0x86, 0x3a, 0x03, 0xb2, 0x37, 0x38, 0xf8, 0x25, 0xfe,
	0x67, 0x24, 0x1e, 0x41, 0xb2, 0x76, 0x36, 0x61, 0xd3, 0x16, 0x4c, 0xbf, 0x23, 0x88, 0xef, 0x2b,
	0x69, 0x71, 0x0e, 0xb1, 0xdb, 0x0b, 0xcf, 0x3a, 0x1d, 0xc3, 0x45, 0xc7, 0xe7, 0x3b, 0xb0, 0x4c,
	0xcd, 0xf6, 0x50, 0xc2, 0x60, 0x9b, 0x1f, 0xf3, 0x4e, 0xd1, 0x9f, 0x7b, 0x8c, 0x2f, 0x77, 0x64,
	0xba, 0x11, 0x77, 0xe9, 0x6b, 0xec, 0x28, 0xef, 0xa9, 0xff, 0x43, 0x37, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x7c, 0xb2, 0x25, 0xb2, 0x5c, 0x02, 0x00, 0x00,
}
