// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListReq) Reset()         { *m = GetListReq{} }
func (m *GetListReq) String() string { return proto.CompactTextString(m) }
func (*GetListReq) ProtoMessage()    {}
func (*GetListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{0}
}

func (m *GetListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListReq.Unmarshal(m, b)
}
func (m *GetListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListReq.Marshal(b, m, deterministic)
}
func (m *GetListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListReq.Merge(m, src)
}
func (m *GetListReq) XXX_Size() int {
	return xxx_messageInfo_GetListReq.Size(m)
}
func (m *GetListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetListReq proto.InternalMessageInfo

type Error struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetListResp struct {
	List                 []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListResp) Reset()         { *m = GetListResp{} }
func (m *GetListResp) String() string { return proto.CompactTextString(m) }
func (*GetListResp) ProtoMessage()    {}
func (*GetListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_856864ca6250a18a, []int{2}
}

func (m *GetListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResp.Unmarshal(m, b)
}
func (m *GetListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResp.Marshal(b, m, deterministic)
}
func (m *GetListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResp.Merge(m, src)
}
func (m *GetListResp) XXX_Size() int {
	return xxx_messageInfo_GetListResp.Size(m)
}
func (m *GetListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResp proto.InternalMessageInfo

func (m *GetListResp) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetListResp) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*GetListReq)(nil), "nezha.chat.common.srv.service.GetListReq")
	proto.RegisterType((*Error)(nil), "nezha.chat.common.srv.service.Error")
	proto.RegisterType((*GetListResp)(nil), "nezha.chat.common.srv.service.GetListResp")
}

func init() { proto.RegisterFile("proto/common/common.proto", fileDescriptor_856864ca6250a18a) }

var fileDescriptor_856864ca6250a18a = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x52, 0x7a, 0x60, 0x31, 0x21, 0xd9, 0xbc,
	0xd4, 0xaa, 0x8c, 0x44, 0xbd, 0xe4, 0x8c, 0xc4, 0x12, 0x3d, 0xa8, 0x44, 0x71, 0x51, 0x99, 0x5e,
	0x71, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x12, 0x0f, 0x17, 0x97, 0x7b, 0x6a, 0x89, 0x4f, 0x66,
	0x71, 0x49, 0x50, 0x6a, 0xa1, 0x92, 0x2e, 0x17, 0xab, 0x6b, 0x51, 0x51, 0x7e, 0x91, 0x90, 0x10,
	0x17, 0x4b, 0x72, 0x7e, 0x4a, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x98, 0x2d, 0x24,
	0xc0, 0xc5, 0x9c, 0x5b, 0x9c, 0x2e, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x62, 0x2a, 0xc5,
	0x72, 0x71, 0xc3, 0x35, 0x17, 0x17, 0x80, 0x34, 0xe5, 0x64, 0x16, 0x97, 0x48, 0x30, 0x2a, 0x30,
	0x6b, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x56, 0x5c, 0xac, 0xa9, 0x20, 0x13, 0xc1, 0xda, 0xb8, 0x8d,
	0x54, 0xf4, 0xf0, 0x3a, 0x47, 0x0f, 0x6c, 0x7b, 0x10, 0x44, 0x8b, 0x51, 0x0e, 0x17, 0x9b, 0x33,
	0x58, 0x89, 0x50, 0x12, 0x17, 0x3b, 0xd4, 0x22, 0x21, 0x4d, 0x02, 0x26, 0x20, 0x7c, 0x23, 0xa5,
	0x45, 0xac, 0xd2, 0xe2, 0x02, 0x25, 0x06, 0x27, 0x8e, 0x28, 0x36, 0x88, 0x9a, 0x24, 0x36, 0x70,
	0xc8, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xe6, 0x9e, 0x57, 0x56, 0x01, 0x00, 0x00,
}
